services:
  shorturl_api:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - REDIS_URI=${REDIS_URI}
      - PORT=${PORT}
      - BASIC_AUTH=${BASIC_AUTH}
      - SHORTENER_PROXY_BASE_URL=${SHORTENER_PROXY_BASE_URL}
      - DEFAULT_TTL=${DEFAULT_TTL}
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: shorturl_redis
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:

